// Te Reo Maori translations for NZ-HIS

export const teReo: Record<string, string> = {
  // Navigation sections
  "Clinical": "Hauora Haumanu",
  "Operations": "Whakahaere",
  "Analytics": "Tātaritanga",
  "AI Tools": "Taputapu AI",

  // Navigation items
  "Dashboard": "Papa Matua",
  "Patients": "Tūroro",
  "Clinical EMR": "Rekōta Hauora",
  "Medications": "Rongoā",
  "CDSS": "Pūnaha Āwhina",
  "Appointments": "Wā Kite",
  "Waitlist": "Rārangi Tatari",
  "Bed Management": "Whakahaere Moenga",
  "ACC Claims": "Kerēme ACC",
  "Hauora Equity": "Ōritenga Hauora",
  "Audit Trail": "Ara Arotake",
  "AI Commander": "Kaiārahi AI",

  // Common terms
  "Patient": "Tūroro",
  "Doctor": "Rata",
  "Nurse": "Tapuhi",
  "Hospital": "Hōhipera",
  "Health": "Hauora",
  "Wellbeing": "Oranga",
  "Family": "Whānau",
  "Welcome": "Nau mai",
  "Search": "Rapu",
  "Add New": "Tāpiri Hou",
  "Save": "Tiaki",
  "Cancel": "Whakakore",
  "Close": "Kati",
  "Delete": "Mukua",
  "Edit": "Whakatika",
  "View": "Tirohia",
  "Status": "Āhua",
  "Active": "Hohe",
  "Completed": "Oti",
  "Pending": "Tatari",

  // Clinical terms
  "Vital Signs": "Tohu Koiora",
  "Blood Pressure": "Pēhanga Toto",
  "Heart Rate": "Pao Manawa",
  "Temperature": "Mahana",
  "Diagnosis": "Tautuhi Mate",
  "Treatment": "Maimoatanga",
  "Prescription": "Tono Rongoā",
  "Discharge": "Tuku Atu",
  "Admission": "Whakaurunga",
  "Emergency": "Ohotata",
  "Surgery": "Pokanga",
  "Alert": "Matohi",
  "Critical": "Tino Nui",
  "Warning": "Whakatūpato",

  // NZ-specific
  "NHI Number": "Tau NHI",
  "ACC Claim": "Kerēme ACC",
  "Iwi": "Iwi",
  "Ethnicity": "Momo Iwi",
  "Region": "Rohe",
  "Whanau": "Whānau",
  "Hauora": "Hauora",
  "Kia ora": "Kia ora",
  "Mana": "Mana",
  "Aroha": "Aroha",
  "Wairua": "Wairua",
  "Tinana": "Tinana",
  "Hinengaro": "Hinengaro",

  // Hauora Equity
  "Health Equity": "Ōritenga Hauora",
  "Cultural Safety": "Haumaru Ahurea",
  "Whanau Ora": "Whānau Ora",
  "Te Whatu Ora": "Te Whatu Ora",
  "Health Targets": "Whāinga Hauora",

  // Dashboard
  "Total Patients": "Tūroro Katoa",
  "Active Admissions": "Whakaurunga Hohe",
  "Today's Appointments": "Wā Kite o Tēnei Rā",
  "Waitlist Count": "Rārangi Tatari",
  "Patient Census": "Tatauranga Tūroro",
  "Demographics": "Tatauranga Taupori",
  "Quality Metrics": "Inenga Kounga",
  "Activity Feed": "Hongere Mahi",

  // Greetings by time
  "Good Morning": "Ata mārie",
  "Good Afternoon": "Ahiahi mārie",
  "Good Evening": "Pō mārie",

  // Page titles & subtitles
  "Electronic Medical Records": "Rekōta Hauora Hiko",
  "Select a patient to view or create notes": "Kōwhiria he tūroro hei tiro, hei hanga tuhinga rānei",
  "Search patients...": "Rapu tūroro...",
  "Patient Management": "Whakahaere Tūroro",
  "Register New Patient": "Rēhita Tūroro Hou",
  "Register Patient": "Rēhita Tūroro",
  "Admitted": "Kua whakaurua",
  "Discharged": "Kua tukua",
  "notes": "tuhinga",
  "Appointments Schedule": "Maramataka Wā Kite",
  "Appointment schedule and booking": "Maramataka me te whakatau wā kite",
  "Surgical Waitlist": "Rārangi Tatari Pokanga",
  "Active Alerts": "Matohi Hohe",
  "Clinical Pathways": "Ara Haumanu",
  "NEWS2 Calculator": "Tatau NEWS2",
  "Falls Risk Assessment": "Aromatawai Tūraru Hinga",
  "Falls Risk": "Tūraru Hinga",
  "Prescribe Medication": "Tono Rongoā",
  "Prescribe": "Tono",
  "Drug Interactions": "Pānga Rongoā",
  "Drug Interaction Warning": "Whakatūpato Pānga Rongoā",
  "Bed Occupancy": "Noho Moenga",
  "Total Beds": "Moenga Katoa",
  "Occupied": "Kua nohoia",
  "Available": "Wātea",
  "Cleaning": "Horoi ana",
  "Maintenance": "Tiaki ana",
  "Cleaning / Maintenance": "Horoi / Tiaki",
  "Claims": "Kerēme",
  "New Claim": "Kerēme Hou",
  "Lodge Claim": "Tuku Kerēme",
  "Lodge New ACC Claim": "Tuku Kerēme ACC Hou",
  "Lodged": "Kua tukua",
  "Accepted": "Kua whakaaetia",
  "Declined": "Kua whakahēngia",
  "Closed": "Kua katia",
  "Filters": "Tātari",
  "All": "Katoa",
  "Date Range": "Roanga Rā",
  "Action": "Mahi",
  "Severity": "Taumaha",
  "Entity": "Hinonga",
  "Timestamp": "Wā Tohu",
  "User": "Kaiwhakamahi",
  "Details": "Taipitopito",
  "Previous": "Mua",
  "Next": "Panuku",
  "AI Clinical Commander": "Kaiārahi Haumanu AI",
  "Commander Mode": "Aratau Kaiārahi",
  "Acknowledge": "Whakaae",
  "Resolve": "Whakatau",
  "Calculate": "Tatau",
  "Calculate NEWS2 Score": "Tatau Kaute NEWS2",
  "Calculate Falls Risk": "Tatau Tūraru Hinga",
  "Record Vitals": "Tuhi Tohu Koiora",
  "Discharge Patient": "Tuku Tūroro",
  "Sign Out": "Takiputa",
  "Loading...": "E uta ana...",
  "No data": "Kāore he raraunga",
  "No patients found": "Kāore he tūroro i kitea",
  "Department": "Tari",
  "Priority": "Mana Matua",
  "urgent": "kōhukihuki",
  "semi-urgent": "āhua kōhukihuki",
  "routine": "tikanga",
  "Urgent": "Kōhukihuki",
  "Semi-urgent": "Āhua kōhukihuki",
  "Routine": "Tikanga",
  "waiting": "e tatari ana",
  "scheduled": "kua whakaritea",
  "completed": "kua oti",
  "cancelled": "kua whakakore",
  "Today": "Tēnei rā",
  "Last 24 hours": "24 hāora whakamutunga",
  "Last 7 days": "7 rā whakamutunga",
  "Last 30 days": "30 rā whakamutunga",
  "Patient Census Trend": "Ia Tatauranga Tūroro",
  "Patient Demographics": "Tatauranga Taupori Tūroro",
  "Department Bed Management": "Whakahaere Moenga Tari",
  "NZ Health Targets": "Whāinga Hauora o Aotearoa",
  "Real-time Activity Feed": "Hongere Mahi Wā-Tūturu",
  "Overall Occupancy": "Noho Whānui",
  "Clinical Decision Support": "Tautoko Whakatau Haumanu",
  "Alerts, pathways, and clinical scoring tools": "Matohi, ara, me ngā taputapu kaute haumanu",
  "NEWS2 Score Calculator": "Tatau Kaute NEWS2",
  "No clinical alerts at this time.": "Kāore he matohi haumanu i tēnei wā.",
  "No clinical pathways configured.": "Kāore he ara haumanu i whakaritea.",
  "No medications prescribed yet.": "Kāore anō kia tohua he rongoā.",
  "No claims found": "Kāore he kerēme i kitea",
  "No audit logs found": "Kāore he pūrongo arotake i kitea",
  "No bed data available": "Kāore he raraunga moenga e wātea ana",
  "Audit Logs": "Pūrongo Arotake",
  "Recommended Interventions": "Ngā Whakauru e Tūtohua ana",
  "NHI-based patient registry": "Rēhita tūroro ā-NHI",
  "First Name": "Ingoa Tuatahi",
  "Last Name": "Ingoa Whakamutunga",
  "Date of Birth": "Rā Whānau",
  "Gender": "Ira Tangata",
  "Male": "Tāne",
  "Female": "Wahine",
  "Other": "Ētahi atu",
  "All Ethnicities": "Momo Iwi Katoa",
  "appts": "wā kite",
  "days waiting": "rā e tatari ana",
  "patients waiting": "tūroro e tatari ana",
  "Discontinue": "Whakamutu",
  "Active Claims": "Kerēme Hohe",
  "Total Claim Costs": "Utu Kerēme Katoa",
  "Cost by Type": "Utu mā te Momo",
  "Claim Events": "Tauārai Kerēme",
  "Injury Date": "Rā Whara",
  "Injury Description": "Whakaahuatanga Whara",
  "Injury Code (optional)": "Waehere Whara (kōwhiringa)",
  "Claim Type": "Momo Kerēme",
  "Dose": "Inenga",
  "Route": "Huarahi",
  "Frequency": "Auautanga",
  "Instructions": "Tohutohu",
  "Medication": "Rongoā",
  "Advance to": "Whakaahu ki",
  "Prescribed by": "I tohua e",
  "on": "i te",
  "active prescriptions": "tono rongoā hohe",
  "All Time": "Wā Katoa",
  "All Actions": "Mahi Katoa",
  "All Severities": "Taumaha Katoa",
  "All Entities": "Hinonga Katoa",
  "entries": "tāuru",
  "Page": "Whārangi",
  "of": "o",
  "Hauora Equity — Oritenga Hauora": "Ōritenga Hauora",
  "Loading equity data...": "E uta ana i ngā raraunga ōritenga...",
  "Wait Time by Ethnicity (minutes)": "Wā Tatari mā te Momo Iwi (meneti)",
  "Average wait times across departments — Maori vs non-Maori": "Wā tatari toharite i ngā tari — Māori ki tauiwi",
  "Admission Rate by Ethnicity (per 1,000)": "Pāpātanga Whakaurunga mā te Momo Iwi (ia 1,000)",
  "Hospital admission rates by condition": "Pāpātanga whakaurunga hōhipera mā te āhua mate",
  "Cultural Safety Score": "Kaute Haumaru Ahurea",
  "Whanau Ora Indicators": "Tohu Whānau Ora",
  "Holistic family wellbeing metrics": "Inenga oranga whānau whānui",
  "Te Whatu Ora Equity Targets": "Whāinga Ōritenga o Te Whatu Ora",
  "National equity targets and current progress": "Whāinga ōritenga ā-motu me te kauneke o nāianei",
  "Metric": "Inenga",
  "Target": "Whāinga",
  "Actual": "Tūturu",
  "Te Reo Maori Glossary": "Papakupu Te Reo Māori",
  "Health terminology in Te Reo Maori": "Kupu hauora i Te Reo Māori",
  "Staff Trained": "Kaimahi Kua Whakangungu",
  "Interpreter Access": "Urunga Kaiwhakamāori",
  "Tikanga Compliance": "Whai Tikanga",
  "Patient Satisfaction": "Ngākau Pai o te Tūroro",
  "Family Wellbeing": "Oranga Whānau",
  "Economic Wellbeing": "Oranga Ohanga",
  "Healthy Lifestyles": "Āhua Noho Hauora",
  "Participation": "Whai Wāhi",
  "Cultural Identity": "Tuakiri Ahurea",
  "Accident Compensation Corporation claim management": "Whakahaere kerēme Kaporeihana Āwhina Aituā",
  "claims": "kerēme",
  "Real-time bed occupancy across all wards": "Noho moenga wā-tūturu puta noa i ngā wāhanga",
  "System activity and compliance logging": "Tuhinga mahi pūnaha me te whai ture",
  "Multi-agent AI assistant for clinical, quality, and research support": "Kaiawhina AI maha-māngai mō te haumanu, kounga, me te rangahau",
};

export function getTeReo(key: string): string | undefined {
  return teReo[key];
}

export function getBilingualLabel(english: string): { en: string; mi: string | undefined } {
  return {
    en: english,
    mi: teReo[english],
  };
}

// Chinese Simplified translations for NZ-HIS
export const zhCN: Record<string, string> = {
  // Navigation sections
  "Clinical": "临床",
  "Operations": "运营",
  "Analytics": "数据分析",
  "AI Tools": "AI 工具",

  // Navigation items
  "Dashboard": "仪表盘",
  "Patients": "患者",
  "Clinical EMR": "临床电子病历",
  "Medications": "药物管理",
  "CDSS": "临床决策支持",
  "Appointments": "预约",
  "Waitlist": "候诊名单",
  "Bed Management": "床位管理",
  "ACC Claims": "ACC 理赔",
  "Hauora Equity": "健康公平",
  "Audit Trail": "审计日志",
  "AI Commander": "AI 指挥官",

  // Common terms
  "Patient": "患者",
  "Doctor": "医生",
  "Nurse": "护士",
  "Hospital": "医院",
  "Health": "健康",
  "Wellbeing": "福祉",
  "Family": "家庭",
  "Welcome": "欢迎",
  "Search": "搜索",
  "Add New": "新增",
  "Save": "保存",
  "Cancel": "取消",
  "Close": "关闭",
  "Delete": "删除",
  "Edit": "编辑",
  "View": "查看",
  "Status": "状态",
  "Active": "活跃",
  "Completed": "已完成",
  "Pending": "待处理",

  // Clinical terms
  "Vital Signs": "生命体征",
  "Blood Pressure": "血压",
  "Heart Rate": "心率",
  "Temperature": "体温",
  "Diagnosis": "诊断",
  "Treatment": "治疗",
  "Prescription": "处方",
  "Discharge": "出院",
  "Admission": "入院",
  "Emergency": "急诊",
  "Surgery": "手术",
  "Alert": "警报",
  "Critical": "危急",
  "Warning": "警告",

  // NZ-specific (keep English/NZ terms where appropriate)
  "NHI Number": "NHI 编号",
  "ACC Claim": "ACC 理赔",
  "Iwi": "部落 (Iwi)",
  "Ethnicity": "民族",
  "Region": "地区",
  "Whanau": "家庭 (Whānau)",
  "Hauora": "健康 (Hauora)",

  // Dashboard
  "Total Patients": "患者总数",
  "Active Admissions": "在院患者",
  "Today's Appointments": "今日预约",
  "Waitlist Count": "候诊人数",
  "Patient Census": "患者统计",
  "Demographics": "人口统计",
  "Quality Metrics": "质量指标",
  "Activity Feed": "动态信息",

  // Greetings
  "Good Morning": "早上好",
  "Good Afternoon": "下午好",
  "Good Evening": "晚上好",

  // Hauora/Equity
  "Health Equity": "健康公平",
  "Cultural Safety": "文化安全",
  "Whanau Ora": "家庭健康",
  "Te Whatu Ora": "新西兰卫生部",
  "Health Targets": "健康目标",

  // Page titles & subtitles
  "Electronic Medical Records": "电子病历系统",
  "Select a patient to view or create notes": "选择患者以查看或创建病历",
  "Search patients...": "搜索患者...",
  "Patient Management": "患者管理",
  "Register New Patient": "注册新患者",
  "Register Patient": "注册患者",
  "Admitted": "已入院",
  "Discharged": "已出院",
  "notes": "病历",
  "Appointments Schedule": "预约日程",
  "Appointment schedule and booking": "预约日程和预定",
  "Surgical Waitlist": "手术等候名单",
  "Active Alerts": "活跃警报",
  "Clinical Pathways": "临床路径",
  "NEWS2 Calculator": "NEWS2 评分计算器",
  "Falls Risk Assessment": "跌倒风险评估",
  "Falls Risk": "跌倒风险",
  "Prescribe Medication": "开具处方",
  "Prescribe": "开具处方",
  "Drug Interactions": "药物相互作用",
  "Drug Interaction Warning": "药物相互作用警告",
  "Bed Occupancy": "床位占用",
  "Total Beds": "总床位数",
  "Occupied": "已占用",
  "Available": "可用",
  "Cleaning": "清洁中",
  "Maintenance": "维护中",
  "Cleaning / Maintenance": "清洁 / 维护",
  "Claims": "理赔",
  "New Claim": "新建理赔",
  "Lodge Claim": "提交理赔",
  "Lodge New ACC Claim": "提交新 ACC 理赔",
  "Lodged": "已提交",
  "Accepted": "已接受",
  "Declined": "已拒绝",
  "Closed": "已关闭",
  "Filters": "筛选",
  "All": "全部",
  "Date Range": "日期范围",
  "Action": "操作",
  "Severity": "严重程度",
  "Entity": "实体",
  "Timestamp": "时间戳",
  "User": "用户",
  "Details": "详情",
  "Previous": "上一页",
  "Next": "下一页",
  "AI Clinical Commander": "AI 临床指挥官",
  "Commander Mode": "指挥官模式",
  "Acknowledge": "确认",
  "Resolve": "解决",
  "Calculate": "计算",
  "Calculate NEWS2 Score": "计算 NEWS2 评分",
  "Calculate Falls Risk": "计算跌倒风险",
  "Record Vitals": "记录生命体征",
  "Discharge Patient": "患者出院",
  "Sign Out": "退出登录",
  "Loading...": "加载中...",
  "No data": "暂无数据",
  "No patients found": "未找到患者",
  "Department": "科室",
  "Priority": "优先级",
  "urgent": "紧急",
  "semi-urgent": "半紧急",
  "routine": "常规",
  "Urgent": "紧急",
  "Semi-urgent": "半紧急",
  "Routine": "常规",
  "waiting": "等待中",
  "scheduled": "已安排",
  "completed": "已完成",
  "cancelled": "已取消",
  "Today": "今天",
  "Last 24 hours": "最近24小时",
  "Last 7 days": "最近7天",
  "Last 30 days": "最近30天",
  "Patient Census Trend": "患者统计趋势",
  "Patient Demographics": "患者人口统计",
  "Department Bed Management": "科室床位管理",
  "NZ Health Targets": "新西兰健康目标",
  "Real-time Activity Feed": "实时动态信息",
  "Overall Occupancy": "总体占用率",
  "Clinical Decision Support": "临床决策支持",
  "Alerts, pathways, and clinical scoring tools": "警报、路径和临床评分工具",
  "NEWS2 Score Calculator": "NEWS2 评分计算器",
  "No clinical alerts at this time.": "目前没有临床警报。",
  "No clinical pathways configured.": "尚未配置临床路径。",
  "No medications prescribed yet.": "尚未开具任何处方。",
  "No claims found": "未找到理赔",
  "No audit logs found": "未找到审计日志",
  "No bed data available": "暂无床位数据",
  "Audit Logs": "审计日志",
  "Recommended Interventions": "推荐干预措施",
  "NHI-based patient registry": "基于NHI的患者登记",
  "First Name": "名",
  "Last Name": "姓",
  "Date of Birth": "出生日期",
  "Gender": "性别",
  "Male": "男",
  "Female": "女",
  "Other": "其他",
  "All Ethnicities": "全部民族",
  "appts": "预约",
  "days waiting": "等待天数",
  "patients waiting": "等待中的患者",
  "Discontinue": "停药",
  "Active Claims": "活跃理赔",
  "Total Claim Costs": "理赔总费用",
  "Cost by Type": "按类型费用",
  "Claim Events": "理赔事件",
  "Injury Date": "受伤日期",
  "Injury Description": "伤情描述",
  "Injury Code (optional)": "伤害代码（可选）",
  "Claim Type": "理赔类型",
  "Dose": "剂量",
  "Route": "给药途径",
  "Frequency": "频次",
  "Instructions": "用药说明",
  "Medication": "药物",
  "Advance to": "推进至",
  "Prescribed by": "开具人",
  "on": "于",
  "active prescriptions": "有效处方",
  "All Time": "所有时间",
  "All Actions": "所有操作",
  "All Severities": "所有严重程度",
  "All Entities": "所有实体",
  "entries": "条记录",
  "Page": "第",
  "of": "/",
  "Hauora Equity — Oritenga Hauora": "健康公平",
  "Loading equity data...": "正在加载健康公平数据...",
  "Wait Time by Ethnicity (minutes)": "按民族分类的等待时间（分钟）",
  "Average wait times across departments — Maori vs non-Maori": "各科室平均等待时间 — 毛利人 vs 非毛利人",
  "Admission Rate by Ethnicity (per 1,000)": "按民族分类的入院率（每千人）",
  "Hospital admission rates by condition": "按病症分类的住院率",
  "Cultural Safety Score": "文化安全评分",
  "Whanau Ora Indicators": "家庭健康指标",
  "Holistic family wellbeing metrics": "全面家庭健康指标",
  "Te Whatu Ora Equity Targets": "新西兰卫生部公平目标",
  "National equity targets and current progress": "国家公平目标和当前进展",
  "Metric": "指标",
  "Target": "目标",
  "Actual": "实际",
  "Te Reo Maori Glossary": "毛利语词汇表",
  "Health terminology in Te Reo Maori": "毛利语健康术语",
  "Staff Trained": "已培训员工",
  "Interpreter Access": "口译服务",
  "Tikanga Compliance": "文化规范合规",
  "Patient Satisfaction": "患者满意度",
  "Family Wellbeing": "家庭健康",
  "Economic Wellbeing": "经济状况",
  "Healthy Lifestyles": "健康生活方式",
  "Participation": "社会参与",
  "Cultural Identity": "文化认同",
  "Accident Compensation Corporation claim management": "事故赔偿公司理赔管理",
  "claims": "条理赔",
  "Real-time bed occupancy across all wards": "所有病房的实时床位占用情况",
  "System activity and compliance logging": "系统活动和合规日志",
  "Multi-agent AI assistant for clinical, quality, and research support": "用于临床、质量和研究支持的多智能体AI助手",
};

export function getZhCN(key: string): string | undefined {
  return zhCN[key];
}

export const teReoGlossary = [
  { term: "Hauora", meaning: "Health, wellbeing", context: "Holistic Māori concept of health encompassing physical, mental, spiritual, and family wellbeing" },
  { term: "Whānau", meaning: "Family, extended family", context: "Central to Māori health — health of an individual is tied to the health of their whānau" },
  { term: "Wairua", meaning: "Spirit, spirituality", context: "One of the four cornerstones of Māori health (Te Whare Tapa Whā)" },
  { term: "Tinana", meaning: "Body, physical health", context: "Physical dimension of health in Te Whare Tapa Whā" },
  { term: "Hinengaro", meaning: "Mind, mental health", context: "Mental and emotional dimension of health" },
  { term: "Mana", meaning: "Authority, prestige, power", context: "Relates to patient dignity and cultural respect in healthcare" },
  { term: "Aroha", meaning: "Love, compassion", context: "Fundamental value in healthcare interactions" },
  { term: "Koru", meaning: "Spiral, new growth", context: "Symbol of new life, growth, strength — used in NZ healthcare branding" },
  { term: "Tūroro", meaning: "Patient, sick person", context: "Term for a patient or someone receiving care" },
  { term: "Rongoā", meaning: "Medicine, remedy", context: "Can refer to traditional Māori medicine or modern medications" },
  { term: "Iwi", meaning: "Tribe, people", context: "Important for identifying health needs of specific Māori communities" },
  { term: "Kaitiakitanga", meaning: "Guardianship, stewardship", context: "Responsibility to protect and care for health data and patient welfare" },
  { term: "Whakamana", meaning: "Empowerment", context: "Empowering patients to participate in their own healthcare decisions" },
  { term: "Tika", meaning: "Correct, right, fair", context: "Ethical principle in health research and practice" },
  { term: "Pono", meaning: "True, genuine, honest", context: "Integrity in clinical practice and patient relationships" },
];
