// Te Reo Maori translations for NZ-HIS

export const teReo: Record<string, string> = {
  // Navigation sections
  "Clinical": "Hauora Haumanu",
  "Operations": "Whakahaere",
  "Analytics": "Tātaritanga",
  "AI Tools": "Taputapu AI",

  // Navigation items
  "Dashboard": "Papa Matua",
  "Patients": "Tūroro",
  "Clinical EMR": "Rekōta Hauora",
  "Medications": "Rongoā",
  "CDSS": "Pūnaha Āwhina",
  "Appointments": "Wā Kite",
  "Waitlist": "Rārangi Tatari",
  "Bed Management": "Whakahaere Moenga",
  "ACC Claims": "Kerēme ACC",
  "Hauora Equity": "Ōritenga Hauora",
  "Audit Trail": "Ara Arotake",
  "AI Commander": "Kaiārahi AI",

  // Common terms
  "Patient": "Tūroro",
  "Doctor": "Rata",
  "Nurse": "Tapuhi",
  "Hospital": "Hōhipera",
  "Health": "Hauora",
  "Wellbeing": "Oranga",
  "Family": "Whānau",
  "Welcome": "Nau mai",
  "Search": "Rapu",
  "Add New": "Tāpiri Hou",
  "Save": "Tiaki",
  "Cancel": "Whakakore",
  "Close": "Kati",
  "Delete": "Mukua",
  "Edit": "Whakatika",
  "View": "Tirohia",
  "Status": "Āhua",
  "Active": "Hohe",
  "Completed": "Oti",
  "Pending": "Tatari",

  // Clinical terms
  "Vital Signs": "Tohu Koiora",
  "Blood Pressure": "Pēhanga Toto",
  "Heart Rate": "Pao Manawa",
  "Temperature": "Mahana",
  "Diagnosis": "Tautuhi Mate",
  "Treatment": "Maimoatanga",
  "Prescription": "Tono Rongoā",
  "Discharge": "Tuku Atu",
  "Admission": "Whakaurunga",
  "Emergency": "Ohotata",
  "Surgery": "Pokanga",
  "Alert": "Matohi",
  "Critical": "Tino Nui",
  "Warning": "Whakatūpato",

  // NZ-specific
  "NHI Number": "Tau NHI",
  "ACC Claim": "Kerēme ACC",
  "Iwi": "Iwi",
  "Ethnicity": "Momo Iwi",
  "Region": "Rohe",
  "Whanau": "Whānau",
  "Hauora": "Hauora",
  "Kia ora": "Kia ora",
  "Mana": "Mana",
  "Aroha": "Aroha",
  "Wairua": "Wairua",
  "Tinana": "Tinana",
  "Hinengaro": "Hinengaro",

  // Hauora Equity
  "Health Equity": "Ōritenga Hauora",
  "Cultural Safety": "Haumaru Ahurea",
  "Whanau Ora": "Whānau Ora",
  "Te Whatu Ora": "Te Whatu Ora",
  "Health Targets": "Whāinga Hauora",

  // Dashboard
  "Total Patients": "Tūroro Katoa",
  "Active Admissions": "Whakaurunga Hohe",
  "Today's Appointments": "Wā Kite o Tēnei Rā",
  "Waitlist Count": "Rārangi Tatari",
  "Patient Census": "Tatauranga Tūroro",
  "Demographics": "Tatauranga Taupori",
  "Quality Metrics": "Inenga Kounga",
  "Activity Feed": "Hongere Mahi",

  // Greetings by time
  "Good Morning": "Ata mārie",
  "Good Afternoon": "Ahiahi mārie",
  "Good Evening": "Pō mārie",

  // Page titles & subtitles
  "Electronic Medical Records": "Rekōta Hauora Hiko",
  "Select a patient to view or create notes": "Kōwhiria he tūroro hei tiro, hei hanga tuhinga rānei",
  "Search patients...": "Rapu tūroro...",
  "Patient Management": "Whakahaere Tūroro",
  "Register New Patient": "Rēhita Tūroro Hou",
  "Register Patient": "Rēhita Tūroro",
  "Admitted": "Kua whakaurua",
  "Discharged": "Kua tukua",
  "notes": "tuhinga",
  "Appointments Schedule": "Maramataka Wā Kite",
  "Appointment schedule and booking": "Maramataka me te whakatau wā kite",
  "Surgical Waitlist": "Rārangi Tatari Pokanga",
  "Active Alerts": "Matohi Hohe",
  "Clinical Pathways": "Ara Haumanu",
  "NEWS2 Calculator": "Tatau NEWS2",
  "Falls Risk Assessment": "Aromatawai Tūraru Hinga",
  "Falls Risk": "Tūraru Hinga",
  "Prescribe Medication": "Tono Rongoā",
  "Prescribe": "Tono",
  "Drug Interactions": "Pānga Rongoā",
  "Drug Interaction Warning": "Whakatūpato Pānga Rongoā",
  "Bed Occupancy": "Noho Moenga",
  "Total Beds": "Moenga Katoa",
  "Occupied": "Kua nohoia",
  "Available": "Wātea",
  "Cleaning": "Horoi ana",
  "Maintenance": "Tiaki ana",
  "Cleaning / Maintenance": "Horoi / Tiaki",
  "Claims": "Kerēme",
  "New Claim": "Kerēme Hou",
  "Lodge Claim": "Tuku Kerēme",
  "Lodge New ACC Claim": "Tuku Kerēme ACC Hou",
  "Lodged": "Kua tukua",
  "Accepted": "Kua whakaaetia",
  "Declined": "Kua whakahēngia",
  "Closed": "Kua katia",
  "Filters": "Tātari",
  "All": "Katoa",
  "Date Range": "Roanga Rā",
  "Action": "Mahi",
  "Severity": "Taumaha",
  "Entity": "Hinonga",
  "Timestamp": "Wā Tohu",
  "User": "Kaiwhakamahi",
  "Details": "Taipitopito",
  "Previous": "Mua",
  "Next": "Panuku",
  "AI Clinical Commander": "Kaiārahi Haumanu AI",
  "Commander Mode": "Aratau Kaiārahi",
  "Acknowledge": "Whakaae",
  "Resolve": "Whakatau",
  "Calculate": "Tatau",
  "Calculate NEWS2 Score": "Tatau Kaute NEWS2",
  "Calculate Falls Risk": "Tatau Tūraru Hinga",
  "Record Vitals": "Tuhi Tohu Koiora",
  "Discharge Patient": "Tuku Tūroro",
  "Sign Out": "Takiputa",
  "Loading...": "E uta ana...",
  "No data": "Kāore he raraunga",
  "No patients found": "Kāore he tūroro i kitea",
  "Department": "Tari",
  "Priority": "Mana Matua",
  "urgent": "kōhukihuki",
  "semi-urgent": "āhua kōhukihuki",
  "routine": "tikanga",
  "Urgent": "Kōhukihuki",
  "Semi-urgent": "Āhua kōhukihuki",
  "Routine": "Tikanga",
  "waiting": "e tatari ana",
  "scheduled": "kua whakaritea",
  "completed": "kua oti",
  "cancelled": "kua whakakore",
  "Today": "Tēnei rā",
  "Last 24 hours": "24 hāora whakamutunga",
  "Last 7 days": "7 rā whakamutunga",
  "Last 30 days": "30 rā whakamutunga",
  "Patient Census Trend": "Ia Tatauranga Tūroro",
  "Patient Demographics": "Tatauranga Taupori Tūroro",
  "Department Bed Management": "Whakahaere Moenga Tari",
  "NZ Health Targets": "Whāinga Hauora o Aotearoa",
  "Real-time Activity Feed": "Hongere Mahi Wā-Tūturu",
  "Overall Occupancy": "Noho Whānui",
  "Clinical Decision Support": "Tautoko Whakatau Haumanu",
  "Alerts, pathways, and clinical scoring tools": "Matohi, ara, me ngā taputapu kaute haumanu",
  "NEWS2 Score Calculator": "Tatau Kaute NEWS2",
  "No clinical alerts at this time.": "Kāore he matohi haumanu i tēnei wā.",
  "No clinical pathways configured.": "Kāore he ara haumanu i whakaritea.",
  "No medications prescribed yet.": "Kāore anō kia tohua he rongoā.",
  "No claims found": "Kāore he kerēme i kitea",
  "No audit logs found": "Kāore he pūrongo arotake i kitea",
  "No bed data available": "Kāore he raraunga moenga e wātea ana",
  "Audit Logs": "Pūrongo Arotake",
  "Recommended Interventions": "Ngā Whakauru e Tūtohua ana",
  "NHI-based patient registry": "Rēhita tūroro ā-NHI",
  "First Name": "Ingoa Tuatahi",
  "Last Name": "Ingoa Whakamutunga",
  "Date of Birth": "Rā Whānau",
  "Gender": "Ira Tangata",
  "Male": "Tāne",
  "Female": "Wahine",
  "Other": "Ētahi atu",
  "All Ethnicities": "Momo Iwi Katoa",
  "appts": "wā kite",
  "days waiting": "rā e tatari ana",
  "patients waiting": "tūroro e tatari ana",
  "Discontinue": "Whakamutu",
  "Active Claims": "Kerēme Hohe",
  "Total Claim Costs": "Utu Kerēme Katoa",
  "Cost by Type": "Utu mā te Momo",
  "Claim Events": "Tauārai Kerēme",
  "Injury Date": "Rā Whara",
  "Injury Description": "Whakaahuatanga Whara",
  "Injury Code (optional)": "Waehere Whara (kōwhiringa)",
  "Claim Type": "Momo Kerēme",
  "Dose": "Inenga",
  "Route": "Huarahi",
  "Frequency": "Auautanga",
  "Instructions": "Tohutohu",
  "Medication": "Rongoā",
  "Advance to": "Whakaahu ki",
  "Prescribed by": "I tohua e",
  "on": "i te",
  "active prescriptions": "tono rongoā hohe",
  "All Time": "Wā Katoa",
  "All Actions": "Mahi Katoa",
  "All Severities": "Taumaha Katoa",
  "All Entities": "Hinonga Katoa",
  "entries": "tāuru",
  "Page": "Whārangi",
  "of": "o",
  "Hauora Equity — Oritenga Hauora": "Ōritenga Hauora",
  "Loading equity data...": "E uta ana i ngā raraunga ōritenga...",
  "Wait Time by Ethnicity (minutes)": "Wā Tatari mā te Momo Iwi (meneti)",
  "Average wait times across departments — Maori vs non-Maori": "Wā tatari toharite i ngā tari — Māori ki tauiwi",
  "Admission Rate by Ethnicity (per 1,000)": "Pāpātanga Whakaurunga mā te Momo Iwi (ia 1,000)",
  "Hospital admission rates by condition": "Pāpātanga whakaurunga hōhipera mā te āhua mate",
  "Cultural Safety Score": "Kaute Haumaru Ahurea",
  "Whanau Ora Indicators": "Tohu Whānau Ora",
  "Holistic family wellbeing metrics": "Inenga oranga whānau whānui",
  "Te Whatu Ora Equity Targets": "Whāinga Ōritenga o Te Whatu Ora",
  "National equity targets and current progress": "Whāinga ōritenga ā-motu me te kauneke o nāianei",
  "Metric": "Inenga",
  "Target": "Whāinga",
  "Actual": "Tūturu",
  "Te Reo Maori Glossary": "Papakupu Te Reo Māori",
  "Health terminology in Te Reo Maori": "Kupu hauora i Te Reo Māori",
  "Staff Trained": "Kaimahi Kua Whakangungu",
  "Interpreter Access": "Urunga Kaiwhakamāori",
  "Tikanga Compliance": "Whai Tikanga",
  "Patient Satisfaction": "Ngākau Pai o te Tūroro",
  "Family Wellbeing": "Oranga Whānau",
  "Economic Wellbeing": "Oranga Ohanga",
  "Healthy Lifestyles": "Āhua Noho Hauora",
  "Participation": "Whai Wāhi",
  "Cultural Identity": "Tuakiri Ahurea",
  "Accident Compensation Corporation claim management": "Whakahaere kerēme Kaporeihana Āwhina Aituā",
  "claims": "kerēme",
  "Real-time bed occupancy across all wards": "Noho moenga wā-tūturu puta noa i ngā wāhanga",
  "System activity and compliance logging": "Tuhinga mahi pūnaha me te whai ture",
  "Multi-agent AI assistant for clinical, quality, and research support": "Kaiawhina AI maha-māngai mō te haumanu, kounga, me te rangahau",

  // Patient detail page - tabs
  "Notes": "Tuhinga",
  "Vitals": "Tohu Koiora",
  "Meds": "Rongoā",
  "Encounters": "Tūtakinga",
  "Labs": "Whakamātautau",
  "Appts": "Wā Kite",

  // Patient detail page - notes
  "New Clinical Note": "Tuhinga Haumanu Hou",
  "Save Note": "Tiaki Tuhinga",
  "Saving...": "E tiaki ana...",
  "SUBJECTIVE": "WHAKAARO",
  "OBJECTIVE": "TIROHANGA",
  "ASSESSMENT": "AROMATAWAI",
  "PLAN": "MAHERE",
  "SUBJECTIVE / HISTORY": "WHAKAARO / HĪTORI",
  "OBJECTIVE / FINDINGS": "TIROHANGA / KITENGA",

  // Vital signs
  "Record Vital Signs": "Tuhi Tohu Koiora",
  "Heart Rate (bpm)": "Pao Manawa (pao/min)",
  "Respiratory Rate": "Pūkahukahu",
  "Respiratory Rate (breaths/min)": "Pūkahukahu (hā/min)",
  "Oxygen Saturation (%)": "Haukō (%)",
  "Supplemental O2": "Haukō Tāpiri",
  "Systolic BP (mmHg)": "Pēhanga Toto Runga (mmHg)",
  "Diastolic BP (mmHg)": "Pēhanga Toto Raro (mmHg)",
  "Temperature (C)": "Mahana (°C)",
  "SpO2 (%)": "Haukō (%)",
  "Pain Score (0-10)": "Kaute Mamae (0-10)",
  "Consciousness (AVPU)": "Mauri (AVPU)",
  "A - Alert": "A - Mauri Ora",
  "V - Voice": "V - Reo",
  "P - Pain": "P - Mamae",
  "U - Unresponsive": "U - Kāore e whakautu",
  "Vitals Trend": "Ia Tohu Koiora",
  "No vital signs recorded yet.": "Kāore anō kia tuhia he tohu koiora.",
  "Current NEWS2:": "NEWS2 o nāianei:",

  // Demographics
  "DOB": "Rā Whānau",
  "Phone": "Waea",
  "Email": "Īmēra",
  "Address": "Wāhitau",
  "Iwi:": "Iwi:",
  "yrs": "tau",

  // Medications
  "Select medication": "Kōwhiria rongoā",
  "Select patient": "Kōwhiria tūroro",
  "Select frequency": "Kōwhiria auautanga",
  "Additional instructions...": "Tohutohu tāpiri...",
  "Oral": "Ā-waha",
  "IV": "Ā-ia",
  "IM": "Ā-uaua",
  "SC": "Ā-kiri raro",
  "Topical": "Ā-kiri",
  "Inhaled": "Ā-hā",
  "Prescribing...": "E tono ana...",
  "No medications prescribed for this patient.": "Kāore he rongoā i tohua mō tēnei tūroro.",

  // Discharge workflow
  "Discharge Workflow": "Tukanga Tuku Atu",
  "Step 1: Confirm Diagnosis": "Hipanga 1: Whakaū Tautuhi Mate",
  "Discharge Diagnosis": "Tautuhi Mate Tuku Atu",
  "Final diagnosis": "Tautuhi mate whakamutunga",
  "Next: Medications": "Panuku: Rongoā",
  "Step 2: Medications on Discharge": "Hipanga 2: Rongoā i te Tuku Atu",
  "Select medications to continue after discharge:": "Kōwhiria ngā rongoā hei whai i muri i te tuku atu:",
  "No active medications.": "Kāore he rongoā hohe.",
  "Back": "Hoki",
  "Next: Follow-up": "Panuku: Whai Muri",
  "Step 3: Follow-up Appointment": "Hipanga 3: Wā Kite Whai Muri",
  "Follow-up Date": "Rā Whai Muri",
  "Next: ACC": "Panuku: ACC",
  "Step 4: ACC Claim Status": "Hipanga 4: Āhua Kerēme ACC",
  "Update Status": "Whakahōu Āhua",
  "No change": "Kāore he huringa",
  "Close claim": "Kati kerēme",
  "Mark for review": "Tohu hei arotake",
  "No ACC claim associated with this patient.": "Kāore he kerēme ACC e hono ana ki tēnei tūroro.",
  "Next: Summary": "Panuku: Whakarāpopoto",
  "Step 5: Discharge Summary": "Hipanga 5: Whakarāpopoto Tuku Atu",
  "Patient:": "Tūroro:",
  "Diagnosis:": "Tautuhi Mate:",
  "Not specified": "Kāore i tohua",
  "Continuing Medications:": "Rongoā e haere tonu ana:",
  "None": "Kore",
  "Discontinued:": "Kua whakamutua:",
  "Follow-up:": "Whai Muri:",
  "ACC Update:": "Whakahōu ACC:",
  "Additional Notes": "Tuhinga Tāpiri",
  "Discharge notes...": "Tuhinga tuku atu...",
  "Confirm Discharge": "Whakaū Tuku Atu",
  "Processing...": "E mahi ana...",

  // Patient detail misc
  "Loading patient...": "E uta ana i te tūroro...",
  "AI Generated": "AI i hanga",
  "Admitted:": "Kua whakaurua:",
  "Discharged:": "Kua tukua:",
  "Provider:": "Kaiwhakarato:",
  "Referred:": "Kua tukua atu:",
  "Target:": "Whāinga:",

  // Table headers
  "Type": "Momo",
  "Test": "Whakamātautau",
  "Value": "Uara",
  "Code": "Waehere",
  "Date": "Rā",
  "Time": "Wā",
  "HR": "PM",
  "BP": "PT",
  "RR": "Hā",
  "Temp": "Mah",
  "AVPU": "AVPU",
  "By": "Nā",

  // Falls risk
  "Age": "Pakeke",
  "Enter patient age": "Tāurua te pakeke o te tūroro",
  "Previous falls in last 12 months": "Hinganga i ngā marama 12 whakamutunga",
  "Mobility impaired / unsteady gait": "Nekeneke kua pāmamae / hīkoi tūwhena",
  "Cognitive impairment / confusion": "Hinengaro kua pāmamae / pōhēhē",
  "Continence issues": "Raruraru pupuri",
  "High-risk medications (sedatives, antihypertensives)": "Rongoā tūraru nui",
  "Visual impairment": "Kanohi kua pāmamae",
  "Risk": "Tūraru",
  "Falls Risk Score:": "Kaute Tūraru Hinga:",

  // CDSS alerts/pathways
  "Timeframe:": "Wā:",
  "Active Alert": "Matohi Hohe",
  "Source:": "Pūtake:",

  // Hauora
  "out of 100": "i te 100",

  // Beds
  "occupied": "kua nohoia",
  "Bed": "Moenga",

  // ACC
  "Injury Code": "Waehere Whara",
  "Total Cost": "Utu Katoa",
  "Describe the injury...": "Whakaahua te whara...",
  "ACC injury code": "Waehere whara ACC",
  "Select claim type": "Kōwhiria momo kerēme",
  "Running:": "E haere ana:",

  // Sidebar
  "Language": "Reo",

  // AI Agent
  "Suggested prompts": "Ngā pātai tūtohua",

  // Commander panel
  "Issue natural language commands across hospital systems": "Tuku tohutohu reo māori puta noa i ngā pūnaha hōhipera",
  "Multi-System Commander": "Kaiārahi Pūnaha Maha",
  "Example commands": "Tohutohu tauira",
  "Generating action plan...": "E hanga ana i te mahere mahi...",
  "Action Plan": "Mahere Mahi",
  "Low Risk": "Tūraru Iti",
  "Medium Risk": "Tūraru Waenga",
  "High Risk": "Tūraru Nui",
  "All actions completed successfully": "Kua oti pai ngā mahi katoa",
  "Executing...": "E mahi ana...",
  "Execute Plan": "Whakahaere Mahere",
  "New Command": "Tohutohu Hou",
  "Describe what you need done across systems...": "Whakaahua ngā mahi e hiahiatia ana puta noa i ngā pūnaha...",

  // Audit date ranges
  "Last 24 Hours": "24 hāora whakamutunga",
  "Last 7 Days": "7 rā whakamutunga",
  "Last 30 Days": "30 rā whakamutunga",

  // Patient list ethnicity items
  "NZ European": "NZ European",
  "Pacific Islander": "Pacific Islander",
  "Asian": "Asian",
  "Māori": "Māori",

  // Appointments enhanced
  "New Appointment": "Wā Kite Hou",
  "Book Appointment": "Tāpiri Wā Kite",
  "Check In": "Takiuru",
  "No Show": "Kāore i tae",
  "Reschedule": "Whakarite anō",
  "Upcoming": "Kei te haere mai",
  "Past": "Kua pahure",
  "consultation": "kōrerorero",
  "follow-up": "whai muri",
  "procedure": "tikanga mahi",
  "surgery": "pokanga",
  "checked-in": "kua takiuru",
  "no-show": "kāore i tae",
  "Select provider": "Kōwhiria kaiwhakarato",
  "Date & Time": "Rā me te Wā",
  "Duration": "Roanga",
  "No-shows": "Kāore i tae",
  "No appointments found.": "Kāore he wā kite i kitea.",
  "min": "meneti",
  "minutes": "meneti",

  // Waitlist enhanced
  "Add to Waitlist": "Tāpiri ki te Rārangi",
  "Schedule": "Whakarite",
  "Remove": "Tangohia",
  "Restore": "Whakahoki",
  "Back to Waiting": "Hoki ki te Tatari",
  "Complete": "Whakaoti",
  "Procedure": "Pokanga",
  "Target Date": "Rā Whāinga",
  "Avg Wait": "Tatari Toharite",
  "Breaching Target": "Takahia Whāinga",
  "Total Waiting": "Tatari Katoa",
  "No waitlist entries found.": "Kāore he tāuru rārangi tatari i kitea.",
  "days": "rā",
  "Waiting": "E tatari ana",
  "Scheduled": "Kua whakaritea",
  "Cancelled": "Kua whakakore",

  // Beds enhanced
  "Assign Patient": "Whakarite Tūroro",
  "Transfer": "Whakawhiti",
  "Mark Available": "Tohu Wātea",
  "Destination Bed": "Moenga Ūnga",
  "All Wards": "Wāhanga Katoa",
  "Discharge to Cleaning": "Tuku ki te Horoi",
  "Search beds...": "Rapu moenga...",
  "Bed Actions": "Mahi Moenga",
  "Select a bed": "Kōwhiria he moenga",

  // Medications enhanced
  "All Statuses": "Āhua Katoa",
  "Total Prescriptions": "Tono Rongoā Katoa",
  "Search medications...": "Rapu rongoā...",
  "All Prescribers": "Kaitohu Katoa",
  "ordered": "kua ōtā",
  "verified": "kua manatoko",
  "dispensed": "kua tukua",
  "administered": "kua whakahaeretia",
  "discontinued": "kua whakamutua",

  // General new terms
  "Provider": "Kaiwhakarato",
  "Select department": "Kōwhiria tari",
  "Select status": "Kōwhiria āhua",
  "Select priority": "Kōwhiria mana matua",

  // AI Diagnosis
  "AI Diagnosis": "Tautuhi AI",
  "AI Medical Image Diagnosis": "Tautuhi Whakaahua Rongoā AI",
  "Upload or select a medical image for AI-assisted diagnosis": "Tukuna, kōwhiria rānei he whakaahua rongoā hei tautuhi AI",
  "Submit for AI Analysis": "Tuku mō te Tātaritanga AI",
  "AI Analyzing...": "E tātari ana te AI...",
  "Analyzing medical image with deep learning model...": "E tātari ana i te whakaahua rongoā mā te tauira ako hōhonu...",
  "Diagnosis Report": "Pūrongo Tautuhi",
  "Sample CT Scan — Right Upper Lobe Mass": "Matapae CT Tauira — Puku Rau Runga Katau",
  "Pre-loaded Demo Image": "Whakaahua Whakaatu Kua Utaina",
  "AI-Assisted Radiological Analysis": "Tātaritanga Iraia AI-Āwhina",
  "New Analysis": "Tātaritanga Hou",

  // Referral Management
  "Referral Management": "Whakahaere Tuku Atu",
  "Referrals": "Ngā Tuku Atu",
  "referrals": "ngā tuku atu",
  "New Referral": "Tuku Atu Hou",
  "Total Referrals": "Tuku Atu Katoa",
  "Pending Review": "E Tatari Arotake",
  "Avg Response Time": "Wā Whakautu Toharite",
  "STAT": "STAT",
  "All Priorities": "Mana Matua Katoa",
  "All Departments": "Tari Katoa",
  "Referred By": "Nā te Tuku",
  "From Department": "Mai i te Tari",
  "To Department": "Ki te Tari",
  "Reason for Referral": "Take mō te Tuku Atu",
  "Reason for referral...": "Take mō te tuku atu...",
  "Clinical Summary": "Whakarāpopoto Haumanu",
  "Clinical summary...": "Whakarāpopoto haumanu...",
  "Response Notes": "Tuhinga Whakautu",
  "Enter response notes...": "Tāurua tuhinga whakautu...",
  "Submit Referral": "Tuku Tuku Atu",
  "Submitting...": "E tuku ana...",
  "Accept": "Whakaae",
  "Decline": "Whakahē",
  "Add Notes": "Tāpiri Tuhinga",
  "View Summary": "Tirohia Whakarāpopoto",
  "Create a new inter-department referral": "Waihanga tuku atu hou i waenga tari",
  "Add or update notes for this referral": "Tāpiri, whakahōu rānei tuhinga mō tēnei tuku atu",
  "No referrals found": "Kāore he tuku atu i kitea",
  "Try adjusting your filters or create a new referral": "Whakamātau kia whakarereke i ō tātari, waihangahia rānei he tuku atu hou",
  "Select patient...": "Kōwhiria tūroro...",
  "Timeline": "Rārangi Wā",
  "Requested": "Kua tonoa",
  "by": "nā",

  // Lab Orders
  "Laboratory Orders": "Ōta Taiwhanga",
  "Lab Orders": "Ōta Taiwhanga",
  "orders": "ōta",
  "pending collection": "e tatari kohikohi ana",
  "New Lab Order": "Ōta Taiwhanga Hou",
  "Total Orders": "Ōta Katoa",
  "Pending Collection": "Tatari Kohikohi",
  "In Progress": "Kei te Haere",
  "Critical Results": "Hua Tino Nui",
  "All Orders": "Ōta Katoa",
  "Search orders...": "Rapu ōta...",
  "No lab orders found.": "Kāore he ōta taiwhanga i kitea.",
  "Select test": "Kōwhiria whakamātautau",
  "Specimen": "Tauira",
  "Select specimen": "Kōwhiria tauira",
  "Clinical Notes": "Tuhinga Haumanu",
  "Reason for test, relevant clinical details...": "Take mō te whakamātautau, taipitopito haumanu...",
  "Submit Lab Order": "Tuku Ōta Taiwhanga",
  "Mark Collected": "Tohu Kua Kohia",
  "Start Processing": "Tīmata Mahi",
  "Enter Results": "Tāuru Hua",
  "View Results": "Tirohia Hua",
  "Result Value": "Uara Hua",
  "Unit": "Waeine",
  "Reference Range": "Awhe Tohutoro",
  "Interpretation": "Whakamārama",
  "Select interpretation": "Kōwhiria whakamārama",
  "Normal": "Noa",
  "Abnormal": "Rerekē",
  "CRITICAL": "TINO NUI",
  "Result Notes": "Tuhinga Hua",
  "Additional notes on result...": "Tuhinga tāpiri mō te hua...",
  "Complete with Results": "Whakaoti me ngā Hua",
  "Results": "Hua",
  "Ordered": "Kua ōtā",
  "Collected": "Kua kohia",
  "Blood": "Toto",
  "Urine": "Mimi",
  "CSF": "CSF",
  "Swab": "Muku",
  "Tissue": "Kiko",
  "collected": "kua kohia",
  "in-progress": "kei te haere",

  // Allergy Management
  "Allergies": "Mate Kiri",
  "Allergy Management": "Whakahaere Mate Kiri",
  "active allergies": "mate kiri hohe",
  "Record Allergy": "Tuhi Mate Kiri",
  "New Allergy Record": "Tuhinga Mate Kiri Hou",
  "Total Active Allergies": "Mate Kiri Hohe Katoa",
  "Drug Allergies": "Mate Kiri Rongoā",
  "Life-Threatening": "Whakaraerae Koiora",
  "Patients with Allergies": "Tūroro me ngā Mate Kiri",
  "Search allergies...": "Rapu mate kiri...",
  "All Types": "Momo Katoa",
  "Allergen": "Mate Kiri",
  "e.g. Penicillin, Peanuts, Latex": "hei tauira Penicillin, Pīnati, Rāteki",
  "Reaction Description": "Whakaahuatanga Urupare",
  "Describe the reaction (e.g. Anaphylaxis, Rash, Hives)...": "Whakaahua te urupare (hei tauira: Anaphylaxis, Kiri puku, Kiri mamae)...",
  "Onset Date": "Rā Tīmata",
  "optional": "kōwhiringa",
  "Additional notes...": "Tuhinga tāpiri...",
  "Reaction": "Urupare",
  "Onset": "Tīmatanga",
  "Mark Inactive": "Tohu Kore Hohe",
  "Edit Allergy": "Whakatika Mate Kiri",
  "No allergies recorded.": "Kāore he mate kiri i tuhia.",

  // Incident Reports
  "Incident Reports": "Pūrongo Aituā",
  "Track and manage clinical incidents and near-misses": "Aroturuki me te whakahaere aituā haumanu me ngā tata-hapa",
  "New Incident Report": "Pūrongo Aituā Hou",
  "Report New Incident": "Pūrongo Aituā Hou",
  "Open Incidents": "Aituā Tuwhera",
  "Under Investigation": "Kei raro i te Tirotiro",
  "Major / Catastrophic": "Nui / Aituā Rahi",
  "Resolved This Month": "Kua Whakatau i Tēnei Marama",
  "Fall": "Hinga",
  "Medication Error": "Hapa Rongoā",
  "Adverse Reaction": "Urupare Kino",
  "Equipment Failure": "Hapa Taputapu",
  "Near Miss": "Tata-Hapa",
  "Minor": "Iti",
  "Moderate": "Āhua Nui",
  "Major": "Nui",
  "Catastrophic": "Aituā Rahi",
  "Reported": "Kua Pūrongotia",
  "Investigating": "Kei te Tirotiro",
  "Resolved": "Kua Whakatau",
  "Location": "Wāhi",
  "Ward / department where incident occurred": "Wāhanga / tari i puta ai te aituā",
  "Description": "Whakaahuatanga",
  "Describe the incident in detail...": "Whakaahua te aituā i te taipitopito...",
  "Immediate Action Taken": "Mahi Tere i Mahia",
  "What was done immediately after the incident?": "He aha i mahia i muri tonu i te aituā?",
  "Submit Incident Report": "Tuku Pūrongo Aituā",
  "No incidents found": "Kāore he aituā i kitea",
  "Root Cause": "Pūtake",
  "Add Root Cause": "Tāpiri Pūtake",
  "Describe the root cause...": "Whakaahua te pūtake...",
  "Outcome": "Hua",
  "Describe the outcome...": "Whakaahua te hua...",
  "Preventive Measures": "Ārai Aituā",
  "What measures will prevent recurrence?": "He aha ngā ārai hei aukati i te hoki anō?",
  "Resolve Incident": "Whakatau Aituā",
  "Investigate": "Tirotiro",
  "Reported by": "Nā te pūrongo",

  // Staff Management
  "Staff Management": "Whakahaere Kaimahi",
  "Staff directory and role management": "Rārangi kaimahi me te whakahaere tūranga",
  "Total Staff": "Kaimahi Katoa",
  "Doctors": "Ngā Rata",
  "Nurses": "Ngā Tapuhi",
  "Other Staff": "Kaimahi Kē",
  "All Roles": "Tūranga Katoa",
  "Admin": "Kaiwhakahaere",
  "Receptionist": "Kaiwhakatau",
  "Pharmacist": "Kairongoā",
  "Lab Tech": "Kaimahi Taiwhanga",
  "Radiologist": "Kaimātai Irirangi",
  "Search staff...": "Rapu kaimahi...",
  "No staff found": "Kāore he kaimahi i kitea",
  "Name": "Ingoa",
  "Role": "Tūranga",
  "Speciality": "Mātauranga Motuhake",
  "HPI Number": "Tau HPI",
  "HPI": "HPI",
  "View Profile": "Tirohia Kōtaha",
  "Staff Profile": "Kōtaha Kaimahi",
  "Joined": "I uru mai",
  "Recent Activity": "Mahi Tata",
  "No recent activity": "Kāore he mahi tata",
  "e.g. Cardiology": "hei tauira Manawa",
};

export function getTeReo(key: string): string | undefined {
  return teReo[key];
}

export function getBilingualLabel(english: string): { en: string; mi: string | undefined } {
  return {
    en: english,
    mi: teReo[english],
  };
}

// Chinese Simplified translations for NZ-HIS
export const zhCN: Record<string, string> = {
  // Navigation sections
  "Clinical": "临床",
  "Operations": "运营",
  "Analytics": "数据分析",
  "AI Tools": "AI 工具",

  // Navigation items
  "Dashboard": "仪表盘",
  "Patients": "患者",
  "Clinical EMR": "临床电子病历",
  "Medications": "药物管理",
  "CDSS": "临床决策支持",
  "Appointments": "预约",
  "Waitlist": "候诊名单",
  "Bed Management": "床位管理",
  "ACC Claims": "ACC 理赔",
  "Hauora Equity": "健康公平",
  "Audit Trail": "审计日志",
  "AI Commander": "AI 指挥官",

  // Common terms
  "Patient": "患者",
  "Doctor": "医生",
  "Nurse": "护士",
  "Hospital": "医院",
  "Health": "健康",
  "Wellbeing": "福祉",
  "Family": "家庭",
  "Welcome": "欢迎",
  "Search": "搜索",
  "Add New": "新增",
  "Save": "保存",
  "Cancel": "取消",
  "Close": "关闭",
  "Delete": "删除",
  "Edit": "编辑",
  "View": "查看",
  "Status": "状态",
  "Active": "活跃",
  "Completed": "已完成",
  "Pending": "待处理",

  // Clinical terms
  "Vital Signs": "生命体征",
  "Blood Pressure": "血压",
  "Heart Rate": "心率",
  "Temperature": "体温",
  "Diagnosis": "诊断",
  "Treatment": "治疗",
  "Prescription": "处方",
  "Discharge": "出院",
  "Admission": "入院",
  "Emergency": "急诊",
  "Surgery": "手术",
  "Alert": "警报",
  "Critical": "危急",
  "Warning": "警告",

  // NZ-specific (keep English/NZ terms where appropriate)
  "NHI Number": "NHI 编号",
  "ACC Claim": "ACC 理赔",
  "Iwi": "部落 (Iwi)",
  "Ethnicity": "民族",
  "Region": "地区",
  "Whanau": "家庭 (Whānau)",
  "Hauora": "健康 (Hauora)",

  // Dashboard
  "Total Patients": "患者总数",
  "Active Admissions": "在院患者",
  "Today's Appointments": "今日预约",
  "Waitlist Count": "候诊人数",
  "Patient Census": "患者统计",
  "Demographics": "人口统计",
  "Quality Metrics": "质量指标",
  "Activity Feed": "动态信息",

  // Greetings
  "Good Morning": "早上好",
  "Good Afternoon": "下午好",
  "Good Evening": "晚上好",

  // Hauora/Equity
  "Health Equity": "健康公平",
  "Cultural Safety": "文化安全",
  "Whanau Ora": "家庭健康",
  "Te Whatu Ora": "新西兰卫生部",
  "Health Targets": "健康目标",

  // Page titles & subtitles
  "Electronic Medical Records": "电子病历系统",
  "Select a patient to view or create notes": "选择患者以查看或创建病历",
  "Search patients...": "搜索患者...",
  "Patient Management": "患者管理",
  "Register New Patient": "注册新患者",
  "Register Patient": "注册患者",
  "Admitted": "已入院",
  "Discharged": "已出院",
  "notes": "病历",
  "Appointments Schedule": "预约日程",
  "Appointment schedule and booking": "预约日程和预定",
  "Surgical Waitlist": "手术等候名单",
  "Active Alerts": "活跃警报",
  "Clinical Pathways": "临床路径",
  "NEWS2 Calculator": "NEWS2 评分计算器",
  "Falls Risk Assessment": "跌倒风险评估",
  "Falls Risk": "跌倒风险",
  "Prescribe Medication": "开具处方",
  "Prescribe": "开具处方",
  "Drug Interactions": "药物相互作用",
  "Drug Interaction Warning": "药物相互作用警告",
  "Bed Occupancy": "床位占用",
  "Total Beds": "总床位数",
  "Occupied": "已占用",
  "Available": "可用",
  "Cleaning": "清洁中",
  "Maintenance": "维护中",
  "Cleaning / Maintenance": "清洁 / 维护",
  "Claims": "理赔",
  "New Claim": "新建理赔",
  "Lodge Claim": "提交理赔",
  "Lodge New ACC Claim": "提交新 ACC 理赔",
  "Lodged": "已提交",
  "Accepted": "已接受",
  "Declined": "已拒绝",
  "Closed": "已关闭",
  "Filters": "筛选",
  "All": "全部",
  "Date Range": "日期范围",
  "Action": "操作",
  "Severity": "严重程度",
  "Entity": "实体",
  "Timestamp": "时间戳",
  "User": "用户",
  "Details": "详情",
  "Previous": "上一页",
  "Next": "下一页",
  "AI Clinical Commander": "AI 临床指挥官",
  "Commander Mode": "指挥官模式",
  "Acknowledge": "确认",
  "Resolve": "解决",
  "Calculate": "计算",
  "Calculate NEWS2 Score": "计算 NEWS2 评分",
  "Calculate Falls Risk": "计算跌倒风险",
  "Record Vitals": "记录生命体征",
  "Discharge Patient": "患者出院",
  "Sign Out": "退出登录",
  "Loading...": "加载中...",
  "No data": "暂无数据",
  "No patients found": "未找到患者",
  "Department": "科室",
  "Priority": "优先级",
  "urgent": "紧急",
  "semi-urgent": "半紧急",
  "routine": "常规",
  "Urgent": "紧急",
  "Semi-urgent": "半紧急",
  "Routine": "常规",
  "waiting": "等待中",
  "scheduled": "已安排",
  "completed": "已完成",
  "cancelled": "已取消",
  "Today": "今天",
  "Last 24 hours": "最近24小时",
  "Last 7 days": "最近7天",
  "Last 30 days": "最近30天",
  "Patient Census Trend": "患者统计趋势",
  "Patient Demographics": "患者人口统计",
  "Department Bed Management": "科室床位管理",
  "NZ Health Targets": "新西兰健康目标",
  "Real-time Activity Feed": "实时动态信息",
  "Overall Occupancy": "总体占用率",
  "Clinical Decision Support": "临床决策支持",
  "Alerts, pathways, and clinical scoring tools": "警报、路径和临床评分工具",
  "NEWS2 Score Calculator": "NEWS2 评分计算器",
  "No clinical alerts at this time.": "目前没有临床警报。",
  "No clinical pathways configured.": "尚未配置临床路径。",
  "No medications prescribed yet.": "尚未开具任何处方。",
  "No claims found": "未找到理赔",
  "No audit logs found": "未找到审计日志",
  "No bed data available": "暂无床位数据",
  "Audit Logs": "审计日志",
  "Recommended Interventions": "推荐干预措施",
  "NHI-based patient registry": "基于NHI的患者登记",
  "First Name": "名",
  "Last Name": "姓",
  "Date of Birth": "出生日期",
  "Gender": "性别",
  "Male": "男",
  "Female": "女",
  "Other": "其他",
  "All Ethnicities": "全部民族",
  "appts": "预约",
  "days waiting": "等待天数",
  "patients waiting": "等待中的患者",
  "Discontinue": "停药",
  "Active Claims": "活跃理赔",
  "Total Claim Costs": "理赔总费用",
  "Cost by Type": "按类型费用",
  "Claim Events": "理赔事件",
  "Injury Date": "受伤日期",
  "Injury Description": "伤情描述",
  "Injury Code (optional)": "伤害代码（可选）",
  "Claim Type": "理赔类型",
  "Dose": "剂量",
  "Route": "给药途径",
  "Frequency": "频次",
  "Instructions": "用药说明",
  "Medication": "药物",
  "Advance to": "推进至",
  "Prescribed by": "开具人",
  "on": "于",
  "active prescriptions": "有效处方",
  "All Time": "所有时间",
  "All Actions": "所有操作",
  "All Severities": "所有严重程度",
  "All Entities": "所有实体",
  "entries": "条记录",
  "Page": "第",
  "of": "/",
  "Hauora Equity — Oritenga Hauora": "健康公平",
  "Loading equity data...": "正在加载健康公平数据...",
  "Wait Time by Ethnicity (minutes)": "按民族分类的等待时间（分钟）",
  "Average wait times across departments — Maori vs non-Maori": "各科室平均等待时间 — 毛利人 vs 非毛利人",
  "Admission Rate by Ethnicity (per 1,000)": "按民族分类的入院率（每千人）",
  "Hospital admission rates by condition": "按病症分类的住院率",
  "Cultural Safety Score": "文化安全评分",
  "Whanau Ora Indicators": "家庭健康指标",
  "Holistic family wellbeing metrics": "全面家庭健康指标",
  "Te Whatu Ora Equity Targets": "新西兰卫生部公平目标",
  "National equity targets and current progress": "国家公平目标和当前进展",
  "Metric": "指标",
  "Target": "目标",
  "Actual": "实际",
  "Te Reo Maori Glossary": "毛利语词汇表",
  "Health terminology in Te Reo Maori": "毛利语健康术语",
  "Staff Trained": "已培训员工",
  "Interpreter Access": "口译服务",
  "Tikanga Compliance": "文化规范合规",
  "Patient Satisfaction": "患者满意度",
  "Family Wellbeing": "家庭健康",
  "Economic Wellbeing": "经济状况",
  "Healthy Lifestyles": "健康生活方式",
  "Participation": "社会参与",
  "Cultural Identity": "文化认同",
  "Accident Compensation Corporation claim management": "事故赔偿公司理赔管理",
  "claims": "条理赔",
  "Real-time bed occupancy across all wards": "所有病房的实时床位占用情况",
  "System activity and compliance logging": "系统活动和合规日志",
  "Multi-agent AI assistant for clinical, quality, and research support": "用于临床、质量和研究支持的多智能体AI助手",

  // Patient detail page - tabs
  "Notes": "病历笔记",
  "Vitals": "生命体征",
  "Meds": "药物",
  "Encounters": "就诊记录",
  "Labs": "检验结果",
  "Appts": "预约",

  // Patient detail page - notes
  "New Clinical Note": "新建临床笔记",
  "Save Note": "保存笔记",
  "Saving...": "保存中...",
  "SUBJECTIVE": "主观",
  "OBJECTIVE": "客观",
  "ASSESSMENT": "评估",
  "PLAN": "计划",
  "SUBJECTIVE / HISTORY": "主观/病史",
  "OBJECTIVE / FINDINGS": "客观/检查结果",
  "Patient's complaint and history...": "患者主诉和病史...",
  "Examination findings, vitals, results...": "检查发现、生命体征、结果...",
  "Diagnosis and clinical reasoning...": "诊断和临床推理...",
  "Treatment plan, medications, follow-up...": "治疗计划、药物、随访...",

  // Vital signs
  "Record Vital Signs": "记录生命体征",
  "Heart Rate (bpm)": "心率 (次/分)",
  "Respiratory Rate": "呼吸频率",
  "Respiratory Rate (breaths/min)": "呼吸频率 (次/分)",
  "Oxygen Saturation (%)": "血氧饱和度 (%)",
  "Supplemental O2": "辅助供氧",
  "Systolic BP (mmHg)": "收缩压 (mmHg)",
  "Diastolic BP (mmHg)": "舒张压 (mmHg)",
  "Temperature (C)": "体温 (°C)",
  "SpO2 (%)": "血氧 (%)",
  "Pain Score (0-10)": "疼痛评分 (0-10)",
  "Consciousness (AVPU)": "意识状态 (AVPU)",
  "A - Alert": "A - 清醒",
  "V - Voice": "V - 语音反应",
  "P - Pain": "P - 疼痛反应",
  "U - Unresponsive": "U - 无反应",
  "Vitals Trend": "生命体征趋势",
  "No vital signs recorded yet.": "尚未记录生命体征。",
  "Current NEWS2:": "当前 NEWS2:",

  // Demographics
  "DOB": "出生日期",
  "Phone": "电话",
  "Email": "电子邮件",
  "Address": "地址",
  "Iwi:": "部落:",
  "yrs": "岁",

  // Medications - prescribe form
  "Select medication": "选择药物",
  "Select patient": "选择患者",
  "Select frequency": "选择频次",
  "Additional instructions...": "补充用药说明...",
  "Oral": "口服",
  "IV": "静脉注射",
  "IM": "肌肉注射",
  "SC": "皮下注射",
  "Topical": "外用",
  "Inhaled": "吸入",
  "Prescribing...": "开具中...",
  "No medications prescribed for this patient.": "该患者尚未开具任何处方。",

  // Discharge workflow
  "Discharge Workflow": "出院工作流程",
  "Step 1: Confirm Diagnosis": "第1步：确认诊断",
  "Discharge Diagnosis": "出院诊断",
  "Final diagnosis": "最终诊断",
  "Next: Medications": "下一步：药物",
  "Step 2: Medications on Discharge": "第2步：出院药物",
  "Select medications to continue after discharge:": "选择出院后继续使用的药物：",
  "No active medications.": "无活跃药物。",
  "Back": "返回",
  "Next: Follow-up": "下一步：随访",
  "Step 3: Follow-up Appointment": "第3步：随访预约",
  "Follow-up Date": "随访日期",
  "Next: ACC": "下一步：ACC",
  "Step 4: ACC Claim Status": "第4步：ACC 理赔状态",
  "Update Status": "更新状态",
  "No change": "不变",
  "Close claim": "关闭理赔",
  "Mark for review": "标记待审",
  "No ACC claim associated with this patient.": "该患者无关联的 ACC 理赔。",
  "Next: Summary": "下一步：摘要",
  "Step 5: Discharge Summary": "第5步：出院摘要",
  "Patient:": "患者：",
  "Diagnosis:": "诊断：",
  "Not specified": "未指定",
  "Continuing Medications:": "继续使用的药物：",
  "None": "无",
  "Discontinued:": "已停用的药物：",
  "Follow-up:": "随访：",
  "ACC Update:": "ACC 更新：",
  "Additional Notes": "补充说明",
  "Discharge notes...": "出院备注...",
  "Confirm Discharge": "确认出院",
  "Processing...": "处理中...",

  // Patient detail misc
  "Loading patient...": "加载患者信息...",
  "AI Generated": "AI 生成",
  "Admitted:": "入院：",
  "Discharged:": "出院：",
  "Provider:": "医生：",
  "Referred:": "转诊：",
  "Target:": "目标：",

  // Table headers
  "Type": "类型",
  "Test": "检验项目",
  "Value": "结果值",
  "Code": "编码",
  "Date": "日期",
  "Time": "时间",
  "HR": "心率",
  "BP": "血压",
  "RR": "呼吸",
  "Temp": "体温",
  "AVPU": "意识",
  "By": "记录人",

  // Falls risk
  "Age": "年龄",
  "Enter patient age": "输入患者年龄",
  "Previous falls in last 12 months": "过去12个月内有跌倒史",
  "Mobility impaired / unsteady gait": "行动障碍/步态不稳",
  "Cognitive impairment / confusion": "认知障碍/意识模糊",
  "Continence issues": "排泄问题",
  "High-risk medications (sedatives, antihypertensives)": "高风险药物（镇静剂、降压药）",
  "Visual impairment": "视力障碍",
  "Risk": "风险",
  "Falls Risk Score:": "跌倒风险评分：",

  // CDSS alerts/pathways
  "Timeframe:": "时间范围：",
  "Active Alert": "活跃警报",
  "Source:": "来源：",

  // Hauora
  "out of 100": "/ 100",

  // Beds
  "occupied": "已占用",
  "Bed": "床位",

  // ACC
  "Injury Code": "伤害代码",
  "Total Cost": "总费用",
  "Describe the injury...": "描述伤情...",
  "ACC injury code": "ACC 伤害代码",
  "Select claim type": "选择理赔类型",
  "Running:": "累计：",

  // Sidebar
  "Language": "语言",

  // AI Agent
  "Suggested prompts": "推荐提问",

  // Commander panel
  "Issue natural language commands across hospital systems": "使用自然语言向医院各系统发出指令",
  "Multi-System Commander": "多系统指挥官",
  "Describe what you need done in plain language. Commander Mode will generate a structured action plan spanning multiple hospital systems.": "用自然语言描述您的需求。指挥官模式将生成跨多个医院系统的结构化行动计划。",
  "Example commands": "示例指令",
  "Generating action plan...": "正在生成行动计划...",
  "Action Plan": "行动计划",
  "Low Risk": "低风险",
  "Medium Risk": "中等风险",
  "High Risk": "高风险",
  "All actions completed successfully": "所有操作已成功完成",
  "Executing...": "执行中...",
  "Execute Plan": "执行计划",
  "New Command": "新建指令",
  "Describe what you need done across systems...": "描述您需要跨系统完成的操作...",

  // Audit date ranges
  "Last 24 Hours": "最近24小时",
  "Last 7 Days": "最近7天",
  "Last 30 Days": "最近30天",

  // Patient list ethnicity items
  "NZ European": "新西兰欧裔",
  "Pacific Islander": "太平洋岛民",
  "Asian": "亚裔",
  "Māori": "毛利人",

  // Appointments enhanced
  "New Appointment": "新增预约",
  "Book Appointment": "预约",
  "Check In": "签到",
  "No Show": "未到",
  "Reschedule": "重新安排",
  "Upcoming": "即将到来",
  "Past": "已过",
  "consultation": "问诊",
  "follow-up": "复诊",
  "procedure": "操作",
  "surgery": "手术",
  "checked-in": "已签到",
  "no-show": "未到",
  "Select provider": "选择医生",
  "Date & Time": "日期和时间",
  "Duration": "时长",
  "No-shows": "未到",
  "No appointments found.": "未找到预约。",
  "min": "分钟",
  "minutes": "分钟",

  // Waitlist enhanced
  "Add to Waitlist": "加入候诊",
  "Schedule": "安排",
  "Remove": "移除",
  "Restore": "恢复",
  "Back to Waiting": "返回等待",
  "Complete": "完成",
  "Procedure": "手术/操作",
  "Target Date": "目标日期",
  "Avg Wait": "平均等待",
  "Breaching Target": "超出目标",
  "Total Waiting": "总等待",
  "No waitlist entries found.": "未找到候诊记录。",
  "days": "天",
  "Waiting": "等待中",
  "Scheduled": "已安排",
  "Cancelled": "已取消",

  // Beds enhanced
  "Assign Patient": "分配患者",
  "Transfer": "转移",
  "Mark Available": "标记可用",
  "Destination Bed": "目标床位",
  "All Wards": "所有病房",
  "Discharge to Cleaning": "出院转清洁",
  "Search beds...": "搜索床位...",
  "Bed Actions": "床位操作",
  "Select a bed": "选择床位",

  // Medications enhanced
  "All Statuses": "所有状态",
  "Total Prescriptions": "总处方数",
  "Search medications...": "搜索药物...",
  "All Prescribers": "所有开具人",
  "ordered": "已下达",
  "verified": "已核实",
  "dispensed": "已发药",
  "administered": "已给药",
  "discontinued": "已停用",

  // General new terms
  "Provider": "医生",
  "Select department": "选择科室",
  "Select status": "选择状态",
  "Select priority": "选择优先级",

  // AI Diagnosis
  "AI Diagnosis": "AI 影像诊断",
  "AI Medical Image Diagnosis": "AI 医学影像诊断",
  "Upload or select a medical image for AI-assisted diagnosis": "上传或选择医学影像进行 AI 辅助诊断",
  "Submit for AI Analysis": "提交 AI 分析",
  "AI Analyzing...": "AI 分析中...",
  "Analyzing medical image with deep learning model...": "正在使用深度学习模型分析医学影像...",
  "Diagnosis Report": "诊断报告",
  "Sample CT Scan — Right Upper Lobe Mass": "示例 CT 扫描 — 右上叶肿块",
  "Pre-loaded Demo Image": "预加载演示图像",
  "AI-Assisted Radiological Analysis": "AI 辅助放射学分析",
  "New Analysis": "新建分析",

  // Referral Management
  "Referral Management": "转诊管理",
  "Referrals": "转诊",
  "referrals": "条转诊",
  "New Referral": "新建转诊",
  "Total Referrals": "转诊总数",
  "Pending Review": "待审核",
  "Avg Response Time": "平均响应时间",
  "STAT": "紧急 (STAT)",
  "All Priorities": "所有优先级",
  "All Departments": "所有科室",
  "Referred By": "转诊医生",
  "From Department": "转出科室",
  "To Department": "转入科室",
  "Reason for Referral": "转诊原因",
  "Reason for referral...": "转诊原因...",
  "Clinical Summary": "临床摘要",
  "Clinical summary...": "临床摘要...",
  "Response Notes": "回复备注",
  "Enter response notes...": "输入回复备注...",
  "Submit Referral": "提交转诊",
  "Submitting...": "提交中...",
  "Accept": "接受",
  "Decline": "拒绝",
  "Add Notes": "添加备注",
  "View Summary": "查看摘要",
  "Create a new inter-department referral": "创建新的跨科室转诊",
  "Add or update notes for this referral": "为此转诊添加或更新备注",
  "No referrals found": "未找到转诊记录",
  "Try adjusting your filters or create a new referral": "尝试调整筛选条件或创建新的转诊",
  "Select patient...": "选择患者...",
  "Timeline": "时间线",
  "Requested": "已请求",
  "by": "由",

  // Lab Orders
  "Laboratory Orders": "检验医嘱",
  "Lab Orders": "检验医嘱",
  "orders": "条医嘱",
  "pending collection": "待采集",
  "New Lab Order": "新建检验医嘱",
  "Total Orders": "医嘱总数",
  "Pending Collection": "待采集",
  "In Progress": "进行中",
  "Critical Results": "危急值",
  "All Orders": "全部医嘱",
  "Search orders...": "搜索医嘱...",
  "No lab orders found.": "未找到检验医嘱。",
  "Select test": "选择检验项目",
  "Specimen": "标本",
  "Select specimen": "选择标本类型",
  "Clinical Notes": "临床备注",
  "Reason for test, relevant clinical details...": "检验原因、相关临床详情...",
  "Submit Lab Order": "提交检验医嘱",
  "Mark Collected": "标记已采集",
  "Start Processing": "开始处理",
  "Enter Results": "录入结果",
  "View Results": "查看结果",
  "Result Value": "结果值",
  "Unit": "单位",
  "Reference Range": "参考范围",
  "Interpretation": "解读",
  "Select interpretation": "选择结果解读",
  "Normal": "正常",
  "Abnormal": "异常",
  "CRITICAL": "危急",
  "Result Notes": "结果备注",
  "Additional notes on result...": "结果补充说明...",
  "Complete with Results": "完成并录入结果",
  "Results": "结果",
  "Ordered": "已下达",
  "Collected": "已采集",
  "Blood": "血液",
  "Urine": "尿液",
  "CSF": "脑脊液",
  "Swab": "拭子",
  "Tissue": "组织",
  "collected": "已采集",
  "in-progress": "进行中",

  // Allergy Management
  "Allergies": "过敏管理",
  "Allergy Management": "过敏管理",
  "active allergies": "条活跃过敏记录",
  "Record Allergy": "记录过敏",
  "New Allergy Record": "新增过敏记录",
  "Total Active Allergies": "活跃过敏总数",
  "Drug Allergies": "药物过敏",
  "Life-Threatening": "危及生命",
  "Patients with Allergies": "有过敏记录的患者",
  "Search allergies...": "搜索过敏记录...",
  "All Types": "所有类型",
  "Allergen": "过敏原",
  "e.g. Penicillin, Peanuts, Latex": "例如：青霉素、花生、乳胶",
  "Reaction Description": "反应描述",
  "Describe the reaction (e.g. Anaphylaxis, Rash, Hives)...": "描述过敏反应（例如：过敏性休克、皮疹、荨麻疹）...",
  "Onset Date": "发病日期",
  "optional": "可选",
  "Additional notes...": "补充说明...",
  "Reaction": "反应",
  "Onset": "发病",
  "Mark Inactive": "标记为非活跃",
  "Edit Allergy": "编辑过敏记录",
  "No allergies recorded.": "暂无过敏记录。",

  // Incident Reports
  "Incident Reports": "不良事件报告",
  "Track and manage clinical incidents and near-misses": "追踪和管理临床不良事件和未遂事件",
  "New Incident Report": "新建不良事件报告",
  "Report New Incident": "报告新不良事件",
  "Open Incidents": "待处理事件",
  "Under Investigation": "调查中",
  "Major / Catastrophic": "重大/灾难性",
  "Resolved This Month": "本月已解决",
  "Fall": "跌倒",
  "Medication Error": "用药差错",
  "Adverse Reaction": "不良反应",
  "Equipment Failure": "设备故障",
  "Near Miss": "未遂事件",
  "Minor": "轻微",
  "Moderate": "中度",
  "Major": "重大",
  "Catastrophic": "灾难性",
  "Reported": "已报告",
  "Investigating": "调查中",
  "Resolved": "已解决",
  "Location": "地点",
  "Ward / department where incident occurred": "事件发生的病房/科室",
  "Description": "描述",
  "Describe the incident in detail...": "详细描述事件...",
  "Immediate Action Taken": "已采取的紧急措施",
  "What was done immediately after the incident?": "事件发生后立即采取了什么措施？",
  "Submit Incident Report": "提交不良事件报告",
  "No incidents found": "未找到不良事件",
  "Root Cause": "根本原因",
  "Add Root Cause": "添加根本原因",
  "Describe the root cause...": "描述根本原因...",
  "Outcome": "结果",
  "Describe the outcome...": "描述结果...",
  "Preventive Measures": "预防措施",
  "What measures will prevent recurrence?": "采取哪些措施可以防止再次发生？",
  "Resolve Incident": "解决事件",
  "Investigate": "开始调查",
  "Reported by": "报告人",

  // Staff Management
  "Staff Management": "员工管理",
  "Staff directory and role management": "员工目录和角色管理",
  "Total Staff": "员工总数",
  "Doctors": "医生",
  "Nurses": "护士",
  "Other Staff": "其他员工",
  "All Roles": "所有角色",
  "Admin": "管理员",
  "Receptionist": "前台接待",
  "Pharmacist": "药剂师",
  "Lab Tech": "检验技师",
  "Radiologist": "放射科医生",
  "Search staff...": "搜索员工...",
  "No staff found": "未找到员工",
  "Name": "姓名",
  "Role": "角色",
  "Speciality": "专业",
  "HPI Number": "HPI 编号",
  "HPI": "HPI",
  "View Profile": "查看档案",
  "Staff Profile": "员工档案",
  "Joined": "加入时间",
  "Recent Activity": "近期操作",
  "No recent activity": "暂无近期操作",
  "e.g. Cardiology": "例如：心内科",
};

export function getZhCN(key: string): string | undefined {
  return zhCN[key];
}

export const teReoGlossary = [
  { term: "Hauora", meaning: "Health, wellbeing", context: "Holistic Māori concept of health encompassing physical, mental, spiritual, and family wellbeing" },
  { term: "Whānau", meaning: "Family, extended family", context: "Central to Māori health — health of an individual is tied to the health of their whānau" },
  { term: "Wairua", meaning: "Spirit, spirituality", context: "One of the four cornerstones of Māori health (Te Whare Tapa Whā)" },
  { term: "Tinana", meaning: "Body, physical health", context: "Physical dimension of health in Te Whare Tapa Whā" },
  { term: "Hinengaro", meaning: "Mind, mental health", context: "Mental and emotional dimension of health" },
  { term: "Mana", meaning: "Authority, prestige, power", context: "Relates to patient dignity and cultural respect in healthcare" },
  { term: "Aroha", meaning: "Love, compassion", context: "Fundamental value in healthcare interactions" },
  { term: "Koru", meaning: "Spiral, new growth", context: "Symbol of new life, growth, strength — used in NZ healthcare branding" },
  { term: "Tūroro", meaning: "Patient, sick person", context: "Term for a patient or someone receiving care" },
  { term: "Rongoā", meaning: "Medicine, remedy", context: "Can refer to traditional Māori medicine or modern medications" },
  { term: "Iwi", meaning: "Tribe, people", context: "Important for identifying health needs of specific Māori communities" },
  { term: "Kaitiakitanga", meaning: "Guardianship, stewardship", context: "Responsibility to protect and care for health data and patient welfare" },
  { term: "Whakamana", meaning: "Empowerment", context: "Empowering patients to participate in their own healthcare decisions" },
  { term: "Tika", meaning: "Correct, right, fair", context: "Ethical principle in health research and practice" },
  { term: "Pono", meaning: "True, genuine, honest", context: "Integrity in clinical practice and patient relationships" },
];
